sudo: true
language: python
matrix:
  include:
    - python: 3.6.1
    - python: 3.7
cache:
  pip: true
  directories:
    - "~/.cache/pypoetry"
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env
  - poetry install
script:
  - make coveralls
deploy:
  provider: script
  script: poetry publish --build -u $PYPI_USER -p $PYPI_PWD
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    branch: master
    python: "3.6.1"